### PR TITLE
typo: they --> the

### PR DESCRIPTION
**Pull request by daveloyall**

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks again, Dave! It's nice having someone fix my mistakes.

**Comment by daveloyall** [comment]
No prob Chris.  I really like your blog and I came across a real-life use for your `simplegpg` just yesterday.  Thanks!

Personally, I find gnat-class typos like missing punctuation to be worth fixing.  Polished prose is more fun to read.  That said, if I you prefer I quit opening PRs for typos, I will do so.

**Comment by skeeto** [comment]
Nope, don't stop with the PRs! I like getting these.

Also, come on now, you can't just say you found a real-life use case and 
not elaborate! What's the use case for simplegpg?

**Comment by daveloyall** [comment]
My use case was verifying the GPG signature on a file: https://www.quicklisp.org/beta/

**Pull request closed without merging**
